import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';

const entry=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const closet=Buffer.from(entry.match(/const CLOSET_B64="([A-Za-z0-9+/=]+)";/)?.[1]||'','base64').toString();
assert.ok(closet.includes('function renderPOV('));
const suite=entry.slice(entry.indexOf('function roomContentSignature('));
function source(text,name){const start=text.indexOf(`function ${name}(`);assert.ok(start>=0,name);const next=text.indexOf('\nfunction ',start+1);return text.slice(start,next<0?undefined:next)}
const defaults={shelf:.75,toeKick:64/25.4,faceGap:4/25.4,drawerSideDeduction:1.0625,drawerDepthDeduction:1,drawerHeightDeduction:1.5};
function bankHarness(){let serial=0;const ctx=vm.createContext({Math,Number,Error,DEFAULTS:defaults,PITCH32:32/25.4,n:(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,round:(x,p)=>Math.round(x/p)*p,fmt:v=>v.toFixed(2),uid:()=>`c${++serial}`});
  vm.runInContext(`const system32={nearest(v){return Math.round((v-${9.5/25.4})/PITCH32)*PITCH32+${9.5/25.4}},snapDown(v){return Math.floor((v-${9.5/25.4}+1e-7)/PITCH32)*PITCH32+${9.5/25.4}}};${['makeComponent','fixedShelf','bankShelves','stackDrawers'].map(n=>source(closet,n)).join('\n')}`,ctx);
  const bottom={type:'shelf',kind:'KB',z:defaults.toeKick,thickness:.75},top={type:'shelf',kind:'KM',z:42,thickness:.75},upper={type:'shelf',kind:'adjustable',z:60,thickness:.75};
  const drawers=[0,1,2,3].map((_,i)=>({type:'drawer',variant:'standard',z:3+i*9,height:8.5}));
  return {ctx,s:{components:[bottom,...drawers,top,upper]},bottom,top,upper,drawers};
}
test('mini drawer recalculates the bank on mounting rows and moves only upper shelves',()=>{const h=bankHarness(),r={height:84};h.ctx.stackDrawers(r,h.s);const prior=h.top.z;const mini={type:'drawer',variant:'mini',height:3,z:prior};h.s.components.push(mini);h.ctx.stackDrawers(r,h.s);assert.ok(h.top.z>prior);assert.ok(h.upper.z>h.top.z+.75);assert.ok(h.drawers[0].z>=h.bottom.z+.75+defaults.faceGap-1e-3);for(const d of [...h.drawers,mini]){const row=(d.mountZ-9.5/25.4)/(32/25.4);assert.ok(Math.abs(row-Math.round(row))<1e-3);assert.ok(d.z+d.height<h.top.z)}assert.equal(h.s.components.filter(c=>c.kind==='KB').length,1)});
test('bank rejects a mini drawer that cannot fit without overlapping the top shelf',()=>{const h=bankHarness();h.ctx.stackDrawers({height:58},h.s);h.s.components.push({type:'drawer',variant:'mini',height:3,z:45});assert.throws(()=>h.ctx.stackDrawers({height:44},h.s),/Drawer bank needs/)});
test('adding a drawer to an open section creates one top bank boundary',()=>{const h=bankHarness();h.s.components=h.s.components.filter(c=>c!==h.top);h.ctx.stackDrawers({height:84},h.s);assert.equal(h.s.components.filter(c=>c.kind==='KM').length,1);assert.ok(h.s.components.find(c=>c.kind==='KM').z>h.drawers.at(-1).z+h.drawers.at(-1).height)});

function cameraHarness(){const state={rooms:[],doc:{runs:[]},viewerCamera:null,record:null};const ctx=vm.createContext({state,Math,Number,Error,CAMERA_RADIUS:3,CAMERA_EYE:64,n:(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,pointInPoly:(p,poly)=>p.x>0&&p.x<100&&p.y>0&&p.y<80,wall:id=>state.rooms[0].walls.find(w=>w.id===id),runWidth:r=>r.width,sectionDepth:(r,s)=>s.depth,renderCanvas:()=>{},persistViewerCamera:()=>{},toast:()=>{}});vm.runInContext(['obstacleBasis','cameraFits','setViewerCamera','moveViewer'].map(n=>source(closet,n)).join('\n'),ctx);const points=[{x:0,y:0},{x:100,y:0},{x:100,y:80},{x:0,y:80}],walls=points.map((a,i)=>{const b=points[(i+1)%4],dx=b.x-a.x,dy=b.y-a.y,L=Math.hypot(dx,dy);return{id:`w${i}`,a,b,length:L,ux:dx/L,uy:dy/L,nx:-dy/L,ny:dx/L,roomKey:'main'}});state.rooms=[{key:'main',closed:true,points,walls,obstacles:[]}];return{ctx,state}}
test('camera stops at walls and fixed run footprints but can turn at the blocked edge',()=>{const {ctx,state}=cameraHarness();state.doc.runs=[{wallId:'w0',offset:0,width:100,depth:16,sections:[{depth:16}]}];state.viewerCamera={x:50,y:40,yaw:-Math.PI/2};assert.equal(ctx.cameraFits({x:50,y:17}),false);ctx.moveViewer(100);assert.ok(state.viewerCamera.y>=19);assert.equal(ctx.setViewerCamera({x:50,y:-2}),false);assert.equal(ctx.setViewerCamera({yaw:0}),true);assert.equal(state.viewerCamera.yaw,0)});
test('camera remains usable when a saved room wall normal faces outward',()=>{const {ctx,state}=cameraHarness();state.rooms[0].walls[1].nx*=-1;state.rooms[0].walls[1].ny*=-1;assert.equal(ctx.cameraFits({x:50,y:40}),true);assert.equal(ctx.cameraFits({x:98,y:40}),false)});
test('camera cannot enter a standing-height appliance footprint',()=>{const {ctx,state}=cameraHarness();state.rooms[0].obstacles=[{category:'appliance',x:50,y:40,width:24,depth:18,height:70,rotation:90}];assert.equal(ctx.cameraFits({x:50,y:40}),false);assert.equal(ctx.cameraFits({x:20,y:40}),true)});

test('room recovery is dated, deduplicated, and separate from named revisions',()=>{let db={projects:[{id:'p',state:{points:[{x:0,y:0},{x:10,y:0}]},revisions:[{id:'named',number:1}]}]},serial=0;const ctx=vm.createContext({Map,JSON,Date,Array,now:()=>new Date('2026-09-24T12:34:56Z').toISOString(),uid:()=>`rec${++serial}`,readDB:()=>structuredClone(db),writeDB:v=>{db=structuredClone(v)},getRecord:id=>db.projects.find(p=>p.id===id)});vm.runInContext([source(suite,'roomContentSignature'),source(suite,'captureRoomEntry'),source(suite,'createRecoverySnapshot')].join('\n'),ctx);ctx.captureRoomEntry('p');const changed={points:[{x:0,y:0},{x:20,y:0}]};assert.equal(ctx.createRecoverySnapshot('p',changed).created,true);assert.equal(ctx.createRecoverySnapshot('p',changed).unchanged,true);assert.equal(db.projects[0].recoverySnapshots.length,1);assert.equal(db.projects[0].recoverySnapshots[0].day,'2026-09-24');assert.equal(db.projects[0].revisions[0].id,'named')});

test('POV depth hides farther geometry and picking selects only the visible section',()=>{let image;const canvas={width:0,height:0,getBoundingClientRect:()=>({left:0,top:0,width:640,height:400}),getContext:()=>({fillRect(){},createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),putImageData:v=>{image=v}})};const ctx=vm.createContext({Math,Number,Float32Array,Int32Array,Infinity,state:{rooms:[],viewerCamera:{x:0,y:0,yaw:0,pitch:0}},povFaces:null,$:()=>canvas,render3D:()=>{ctx.povFaces.push({pts:[{x:30,y:-20,z:20},{x:30,y:20,z:20},{x:30,y:20,z:90},{x:30,y:-20,z:90}],fill:'#ff0000',attrs:{'data-section':'behind'}})},povWallFaces:()=>{ctx.povFaces.push({pts:[{x:15,y:-20,z:20},{x:15,y:20,z:20},{x:15,y:20,z:90},{x:15,y:-20,z:90}],fill:'#00ff00',attrs:{'data-section':'front','data-component':'drawer'}})},CAMERA_EYE:64,MOODS:{Ideal:{brightness:1,ambient:0,shadows:0,contrast:1,warmth:0}},visualMood:'Ideal',povImage:{brightness:1.08,ambient:.10,shadows:.35,contrast:1.04,warmth:0,outlines:.68,quality:1.5}});vm.runInContext(['povRasterSize','povFaceColor','renderPOV','povPickAt'].map(n=>source(closet,n)).join('\n'),ctx);ctx.renderPOV();const at=(200*640+320)*4;assert.ok(image.data[at+1]>image.data[at]*3);assert.equal(ctx.povPickAt(320,200).id,'front');assert.equal(ctx.povPickAt(320,200,true).id,'drawer');ctx.state.partSelectMode=true;assert.equal(ctx.povPickAt(320,200).id,'drawer');assert.equal(ctx.povPickAt(-1,200),null)});
test('POV backing dimensions follow display aspect without an unbounded pixel count',()=>{const ctx=vm.createContext({Math,Number,povImage:{quality:1.5}});vm.runInContext(source(closet,'povRasterSize'),ctx);const wide=ctx.povRasterSize({getBoundingClientRect:()=>({width:1000,height:500})}),tall=ctx.povRasterSize({getBoundingClientRect:()=>({width:500,height:1000})});assert.ok(Math.abs(wide.width/wide.height-2)<.01);assert.ok(Math.abs(tall.width/tall.height-.5)<.01);assert.ok(wide.width*wide.height<=950000)});
test('Ideal keeps the restored POV face color and Bright Work increases illumination',()=>{const povImage={brightness:1,ambient:0,shadows:0,contrast:1,warmth:0,outlines:.68,quality:1},ctx=vm.createContext({Math,Number,state:{rooms:[]},n:Number,povImage,MOODS:{Ideal:{brightness:1,ambient:0,shadows:0,contrast:1,warmth:0}},visualMood:'Ideal'});vm.runInContext(source(closet,'povFaceColor'),ctx);const face={pts:[{x:0,y:0,z:0},{x:10,y:0,z:0},{x:10,y:10,z:0}],fill:'#b29f84'};assert.deepEqual(Array.from(ctx.povFaceColor(face)),[174,155,130]);povImage.brightness=1.28;povImage.ambient=.16;assert.ok(ctx.povFaceColor(face)[0]>174)});
test('flat floor and ceiling triangulate an L-shaped room without filling its cutout',()=>{const ctx=vm.createContext({Math});vm.runInContext(source(closet,'roomSurfaceTriangles'),ctx);const points=[{x:0,y:0},{x:10,y:0},{x:10,y:4},{x:4,y:4},{x:4,y:10},{x:0,y:10}],triangles=ctx.roomSurfaceTriangles(points),area=triangles.reduce((sum,[a,b,c])=>sum+Math.abs((b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x))/2,0);assert.equal(area,64)});

function fitHarness(){const run={id:'run1',wallId:'wall1',offset:0,thickness:.75,fillerStart:0,fillerEnd:0,sections:[{id:'a',width:24,locked:true},{id:'b',width:24,locked:false}],partitions:[]};const old={id:'wall1',length:50.25,walls:[]},current={id:'wall1',length:62.25};const state={doc:{runs:[run]},rooms:[{walls:[current]}],dirty:false};const ctx=vm.createContext({state,Map,Math,Number,clone:structuredClone,n:(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,wall:id=>id==='wall1'?current:null,runInterval:r=>[r.offset,r.offset+r.sections.reduce((sum,s)=>sum+s.width,0)+(r.sections.length+1)*r.thickness+(r.fillerStart||0)+(r.fillerEnd||0)],rebuildPartitions:r=>{r.partitions=Array(r.sections.length+1).fill({})},validateRun:r=>r.sections.some(s=>s.width<6||s.width>40)?['Invalid section width']:[]});vm.runInContext(source(closet,'fitRunsToRoom'),ctx);return{ctx,state,old,current,run}}
test('wall resize fits an end-anchored run while retaining section identities and locked widths',()=>{const h=fitHarness();assert.equal(h.ctx.fitRunsToRoom([{walls:[h.old]}]).resized,1);assert.equal(h.run.sections[0].width,24);assert.equal(h.run.sections[1].width,36);assert.equal(h.run.partitions.length,3);assert.equal(h.state.dirty,true);h.old.length=62.25;h.current.length=44.25;assert.equal(h.ctx.fitRunsToRoom([{walls:[h.old]}]).resized,1);assert.equal(h.run.sections[1].width,18)});
test('impossible wall shrink reports a fit conflict and preserves the run',()=>{const h=fitHarness();h.current.length=30;const result=h.ctx.fitRunsToRoom([{walls:[h.old]}]);assert.equal(result.resized,0);assert.match(result.blocked[0],/no valid unlocked section widths/);assert.equal(h.run.sections[1].width,24);assert.equal(h.state.dirty,false)});
test('room handoff refreshes derived drawer sizes before saving a resized run',()=>{const drawer={type:'drawer',boxWidth:20,boxWidthCustom:false},section={width:22,components:[drawer]},state={rooms:[],record:{},doc:{runs:[{sections:[section]}]}};let savedWidth=0;const ctx=vm.createContext({window:{},state,clone:structuredClone,roomSnapshots:()=>[{}],normalizeRoom:x=>x,fitRunsToRoom:()=>{section.width=28;return{resized:1,blocked:[]}},normalizeDoc:()=>{drawer.boxWidth=section.width-defaults.drawerSideDeduction},ensureViewerCamera:()=>{},projectIssues:()=>[],saveToProject:()=>{savedWidth=drawer.boxWidth},render:()=>{},roomConflictMessage:()=>'',toast:()=>{}});vm.runInContext(source(closet,'adoptRoomState'),ctx);ctx.adoptRoomState({},'today',0);assert.equal(savedWidth,28-defaults.drawerSideDeduction)});
test('section type icons build door, drawer, hanging, and shoe configurations',()=>{const s={type:'Open',components:[],door:null},events=[];const ctx=vm.createContext({s,Math,n:Number,balancedAdjustableShelves:(r,section,count)=>Array.from({length:count},()=>({type:'shelf',fixed:false,kind:'adjustable'})),selectedSection:()=>s,applyPreset:type=>{s.type=type;s.components=type==='Shelves'?[{type:'shelf',fixed:false,kind:'adjustable'}]:[];events.push(type)},addDoor:()=>{s.door={type:'single'}}});vm.runInContext([source(closet,'chooseSectionType'),source(closet,'setAdjustableShelfCount')].join('\n'),ctx);ctx.chooseSectionType('Doors');assert.equal(s.type,'Doors');assert.ok(s.door);ctx.chooseSectionType('Drawers');assert.equal(s.type,'Drawers');assert.equal(s.door,null);ctx.chooseSectionType('Double Hang');assert.equal(s.type,'Double Hang');ctx.chooseSectionType('Shoe Shelves');assert.equal(s.type,'Shoe Shelves');assert.equal(s.components[0].kind,'tilted-shoe');ctx.setAdjustableShelfCount({},s,3);assert.equal(s.components.filter(c=>c.kind==='tilted-shoe').length,3);assert.deepEqual(events,['Open','Drawers','Double Hang','Shelves'])});

test('POV keyboard intent combines diagonal walking and diagonal head look',()=>{
  const ctx=vm.createContext({});
  vm.runInContext(source(closet,'povNavigationIntent'),ctx);
  const walk=ctx.povNavigationIntent(new Set(['ArrowUp','ArrowRight']));
  assert.deepEqual({...walk},{forward:1,strafe:1});
  const look=ctx.povNavigationIntent(new Set(['ArrowUp','ArrowRight']),true);
  assert.deepEqual({...look},{yaw:1,pitch:1});
  assert.deepEqual({...ctx.povNavigationIntent(new Set(['ArrowDown','ArrowLeft']),true)},{yaw:-1,pitch:-1});
});

test('POV trackpad zoom changes perspective scale and clamps to a safe range',()=>{
  const state={viewerCamera:{x:0,y:0,yaw:0,pitch:0,zoom:1}};
  let renders=0,persisted=0;
  const ctx=vm.createContext({state,Math,Number,n:(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,persistViewerCamera:()=>persisted++,renderCanvas:()=>renders++});
  vm.runInContext(source(closet,'povZoomByGesture'),ctx);
  assert.equal(ctx.povZoomByGesture(-120),true);
  assert.ok(state.viewerCamera.zoom>1);
  assert.equal(ctx.povZoomByGesture(120),true);
  assert.ok(state.viewerCamera.zoom<1.2);
  ctx.povZoomByGesture(100000);
  assert.equal(state.viewerCamera.zoom,.32);
  assert.equal(renders,3);
  assert.equal(persisted,3);
});
